---
- name: restart go-server 
  service: name=go-server state=restarted
  sudo: yes
  notify:
     - ensure go-server running

- name: ensure go-server running
  wait_for: port={{ gocd.server.port_ssl }} timeout=120 delay=10
