---
- name: install go-agent 
  yum: pkg=go-agent-{{ go_version}} state=installed
  sudo: yes
  # notify:
  # - restart go-agent

# We don't use the RPM bundle agent service as it's not really designed for running multiple agents concurrently.
# Once Go source is available we hope to change it's service to be mult-agent by default, and this logic will be removed.
- name: ensure legacy go-agent service is disabled
  command: /sbin/chkconfig --del go-agent removes=/etc/init.d/go-agent
  sudo: yes

- name: ensure legacy go-agent service is removed
  file: path=/etc/init.d/go-agent state=absent
  sudo: yes

- name: ensure legacy go-agent working directory is removed
  file: path="{{ gocd.agent.work_dir_base }}/go-agent" state=absent
  sudo: yes

- debug: msg="{{ ansible_processor_count }} CPUs and {{ ansible_processor_cores }} core detected.  {{ gocd.agent.instances}} agents will be installed."

- name: Creating additional agents - directory structure.
  file: path="{{ gocd.agent.work_dir_base }}/go-agent{{item}}" mode=0755 owner=go group=go state=directory recurse=true
  with_sequence: "count={{ gocd.agent.instances}}"
  sudo: yes

- file: path="{{ gocd.agent.work_dir_base }}/go-agent{{item}}/config" mode=0755 owner=go group=go state=directory recurse=true
  with_sequence: "count={{ gocd.agent.instances}}"
  sudo: yes

- name: Creating additional agents - defaults.
  template: "src=go-agent-defaults dest=/etc/default/go-agent{{ item }} mode=0644 owner=root group=root"
  with_sequence: "count={{ gocd.agent.instances}}"
  sudo: yes

- name: Creating additional agents - service.
  template: "src=go-agent-service dest=/etc/init.d/go-agent{{ item }} mode=0755 owner=root group=root"
  with_sequence: "count={{ gocd.agent.instances}}"
  sudo: yes

- name: Creating additional agents - bash script.
  template: "src=go-agent-sh dest=/usr/share/go-agent/agent{{ item }}.sh mode=0755 owner=root group=root"
  with_sequence: "count={{ gocd.agent.instances}}"
  sudo: yes

- name: Ensure Go-agents are started and run on startup.
  service: "name=go-agent{{item}} state=started enabled=yes"
  with_sequence: "count={{ gocd.agent.instances}}"
  sudo: yes